import importlib.util
import os
import sys

SRC_DIR = os.path.join(os.path.dirname(__file__), "..", "src")
DEFAULT_CONFIG_PATH = os.path.join(SRC_DIR, "config_default.py")
USER_CONFIG_PATH = os.path.join(SRC_DIR, "config.py")

spec = importlib.util.spec_from_file_location("config_default", DEFAULT_CONFIG_PATH)
if spec is None or spec.loader is None:
    print(f"Could not load default config from {DEFAULT_CONFIG_PATH}")
    sys.exit(1)
default_config = importlib.util.module_from_spec(spec)
spec.loader.exec_module(default_config)

answers = {}
print("--- dryspace-vent config wizard ---\n")
for key, value in default_config.CONFIG.items():
    if key in ["wifi_password"]:
        import getpass
        prompt = f"{key} [{value}]: "
        user_input = getpass.getpass(prompt)
    else:
        prompt = f"{key} [{value}]: "
        user_input = input(prompt)
    if user_input.strip() == "":
        answers[key] = value
    else:
        # Try to cast to int if the default is int
        if isinstance(value, int):
            try:
                answers[key] = int(user_input)
            except Exception:
                answers[key] = value
        else:
            answers[key] = user_input

with open(USER_CONFIG_PATH, "w") as f:
    f.write("# This file is generated by the config wizard. Do not commit to git.\n")
    f.write("CONFIG = " + repr(answers) + "\n")

print(f"\nConfig written to {USER_CONFIG_PATH}\n")
